server:
  port: ${nimble.server.port}

spring:
  application:
    name: ${nimble.spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: ${nimble.eureka.client.service-url.defaultZone}
  instance:
    hostname: ${nimble.eureka.instance.hostname}
    instance-id: ${nimble.eureka.instance.instance-id}

# In spring cloud this setting is closed (default)
feign:
  hystrix:
    enabled: true

logging:
  level:
    root: ${nimble.logging.level.root}
