nimble:
  spring:
    application:
      name: consumer

  server:
    port: 7933

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:7900/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${server.port}

  logging:
    level:
      root: info